#!/usr/bin/env bash
#
# install-into-project.sh — Install Snowball's GitLab Duo integration
# into a local project. Auto-detects the Snowball clone location from
# this script's own path, so Snowball can live anywhere (not just
# ~/Projects/snowball).
#
# Default target is the current working directory; pass a path as the
# first positional argument to override.
#
# Usage:
#   install-into-project.sh [options] [target-dir]
#
#   --force        Overwrite existing files / symlinks
#   --uninstall    Remove Snowball symlinks and generated hooks.json
#   --no-skills    Skip the skills/ symlink (AGENTS.md + hooks.json only)
#   -h, --help     Show this help
#
set -euo pipefail

# --- resolve script and snowball paths (follow symlinks) ---

resolve_script_dir() {
    local src="${BASH_SOURCE[0]}"
    while [ -L "$src" ]; do
        local dir
        dir="$(cd -P "$(dirname "$src")" && pwd)"
        src="$(readlink "$src")"
        [[ "$src" != /* ]] && src="$dir/$src"
    done
    cd -P "$(dirname "$src")" && pwd
}

SCRIPT_DIR="$(resolve_script_dir)"
SNOWBALL_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# --- args ---

force=0
uninstall=0
install_skills=1
target=""

usage() {
    sed -n '3,20p' "$0" | sed 's/^# \{0,1\}//'
}

while [ $# -gt 0 ]; do
    case "$1" in
        --force)      force=1 ;;
        --uninstall)  uninstall=1 ;;
        --no-skills)  install_skills=0 ;;
        -h|--help)    usage; exit 0 ;;
        --)           shift; target="${1:-}"; break ;;
        -*)           echo "error: unknown option: $1" >&2; usage >&2; exit 2 ;;
        *)            target="$1" ;;
    esac
    shift
done

target="${target:-$PWD}"

if [ ! -d "$target" ]; then
    echo "error: target directory does not exist: $target" >&2
    exit 1
fi

target="$(cd "$target" && pwd)"

if [ "$target" = "$SNOWBALL_ROOT" ]; then
    echo "error: target is the Snowball clone itself; nothing to do" >&2
    echo "(open Duo directly in $SNOWBALL_ROOT — files are already in place)" >&2
    exit 1
fi

# --- helpers ---

is_snowball_symlink() {
    local path="$1" expected="$2"
    [ -L "$path" ] || return 1
    local resolved
    resolved="$(readlink "$path")"
    case "$resolved" in
        "$expected"|"$expected/") return 0 ;;
        *) return 1 ;;
    esac
}

remove_with_confirmation() {
    local path="$1" kind="$2" expected_target="$3"
    if is_snowball_symlink "$path" "$expected_target"; then
        rm -f "$path"
        echo "  removed $kind symlink: $path"
    elif [ -e "$path" ] || [ -L "$path" ]; then
        if [ "$force" -eq 1 ]; then
            rm -rf "$path"
            echo "  removed (--force) $kind: $path"
        else
            echo "  refusing to remove $kind (not a Snowball symlink): $path" >&2
            return 1
        fi
    fi
}

# --- uninstall path ---

if [ "$uninstall" -eq 1 ]; then
    echo "Uninstalling Snowball from $target"
    rc=0
    remove_with_confirmation "$target/AGENTS.md" "AGENTS.md" "$SNOWBALL_ROOT/AGENTS.md" || rc=1

    # skills/: handle both the legacy whole-directory symlink and the per-skill model.
    if [ -L "$target/skills" ]; then
        if is_snowball_symlink "$target/skills" "$SNOWBALL_ROOT/skills"; then
            rm -f "$target/skills"
            echo "  removed skills/ symlink (legacy whole-directory install)"
        elif [ "$force" -eq 1 ]; then
            rm -f "$target/skills"
            echo "  removed (--force) skills/ symlink: $target/skills"
        else
            echo "  refusing to remove skills/ symlink (not a Snowball symlink): $target/skills" >&2
            rc=1
        fi
    elif [ -d "$target/skills" ]; then
        removed_skills=0
        for entry in "$target"/skills/*; do
            [ -e "$entry" ] || [ -L "$entry" ] || continue
            name="$(basename "$entry")"
            if [ -L "$entry" ] && is_snowball_symlink "$entry" "$SNOWBALL_ROOT/skills/$name"; then
                rm -f "$entry"
                removed_skills=$((removed_skills + 1))
            fi
        done
        if [ "$removed_skills" -gt 0 ]; then
            echo "  removed $removed_skills Snowball skill symlink(s) from skills/"
        fi
        if rmdir "$target/skills" 2>/dev/null; then
            echo "  removed empty skills/"
        else
            echo "  preserved skills/ (contains project-defined entries)"
        fi
    fi

    hooks_file="$target/.gitlab/duo/hooks.json"
    if [ -f "$hooks_file" ]; then
        if grep -q "$SNOWBALL_ROOT/hooks/run-hook.cmd" "$hooks_file" 2>/dev/null; then
            rm -f "$hooks_file"
            echo "  removed generated hooks.json: $hooks_file"
        elif [ "$force" -eq 1 ]; then
            rm -f "$hooks_file"
            echo "  removed (--force) hooks.json: $hooks_file"
        else
            echo "  refusing to remove hooks.json (not generated by this script): $hooks_file" >&2
            rc=1
        fi
    fi

    # Remove empty .gitlab/duo and .gitlab dirs if we own them
    rmdir "$target/.gitlab/duo" 2>/dev/null && echo "  removed empty .gitlab/duo/" || true
    rmdir "$target/.gitlab" 2>/dev/null && echo "  removed empty .gitlab/" || true

    exit $rc
fi

# --- install path ---

echo "Installing Snowball into $target"
echo "Snowball clone: $SNOWBALL_ROOT"

install_symlink() {
    local src="$1" dst="$2" label="$3"
    if [ ! -e "$src" ]; then
        echo "  skipping $label (source missing: $src)"
        return 0
    fi
    if [ -e "$dst" ] || [ -L "$dst" ]; then
        if is_snowball_symlink "$dst" "$src"; then
            echo "  $label already linked"
            return 0
        fi
        if [ "$force" -ne 1 ]; then
            echo "error: $dst already exists and is not a Snowball symlink" >&2
            echo "       re-run with --force to overwrite, or remove the file first" >&2
            return 1
        fi
        rm -rf "$dst"
    fi
    ln -s "$src" "$dst"
    echo "  linked $label → $src"
}

install_symlink "$SNOWBALL_ROOT/AGENTS.md" "$target/AGENTS.md" "AGENTS.md" || exit 1

if [ "$install_skills" -eq 1 ]; then
    # Per-skill symlinks under <target>/skills/. Project-defined skill directories
    # (anything that isn't a Snowball symlink) are preserved — they represent
    # intentional local overrides and take priority over Snowball's defaults.

    # Migrate legacy whole-directory symlink, if present.
    if [ -L "$target/skills" ]; then
        if is_snowball_symlink "$target/skills" "$SNOWBALL_ROOT/skills"; then
            rm -f "$target/skills"
            echo "  migrated legacy whole-directory skills symlink to per-skill model"
        elif [ "$force" -eq 1 ]; then
            rm -f "$target/skills"
            echo "  removed (--force) existing skills/ symlink"
        else
            echo "error: $target/skills is a symlink to something other than Snowball" >&2
            echo "       re-run with --force to overwrite, or remove the link first" >&2
            exit 1
        fi
    fi

    mkdir -p "$target/skills"

    linked=0
    already=0
    preserved=0
    for src_skill in "$SNOWBALL_ROOT"/skills/*/; do
        [ -d "$src_skill" ] || continue
        name="$(basename "$src_skill")"
        src="$SNOWBALL_ROOT/skills/$name"
        dst="$target/skills/$name"

        if [ -L "$dst" ] && is_snowball_symlink "$dst" "$src"; then
            already=$((already + 1))
            continue
        fi

        if [ -e "$dst" ] || [ -L "$dst" ]; then
            if [ "$force" -eq 1 ]; then
                rm -rf "$dst"
                ln -s "$src" "$dst"
                linked=$((linked + 1))
            else
                preserved=$((preserved + 1))
            fi
            continue
        fi

        ln -s "$src" "$dst"
        linked=$((linked + 1))
    done

    echo "  skills: $linked linked, $already already in place, $preserved project-defined (kept)"
else
    echo "  --no-skills: skipping skills/ symlinks (Duo Agent Skills won't be discoverable)"
fi

# Generate .gitlab/duo/hooks.json with the absolute Snowball path patched in
mkdir -p "$target/.gitlab/duo"
hooks_dst="$target/.gitlab/duo/hooks.json"

if [ -e "$hooks_dst" ] && [ "$force" -ne 1 ]; then
    if grep -q "$SNOWBALL_ROOT/hooks/run-hook.cmd" "$hooks_dst" 2>/dev/null; then
        echo "  .gitlab/duo/hooks.json already points at this Snowball clone"
    else
        echo "error: $hooks_dst already exists; re-run with --force to overwrite" >&2
        exit 1
    fi
else
    cat >"$hooks_dst" <<EOF
{
  "hooks": {
    "SessionStart": [
      {
        "matcher": "startup|resume|clear",
        "hooks": [
          {
            "type": "command",
            "command": "\"$SNOWBALL_ROOT/hooks/run-hook.cmd\" session-start"
          }
        ]
      }
    ]
  }
}
EOF
    echo "  wrote .gitlab/duo/hooks.json (bootstrap path: $SNOWBALL_ROOT/hooks/run-hook.cmd)"
fi

cat <<EOF

Done. Verify with:

  cd "$target"
  ls -la AGENTS.md skills .gitlab/duo/hooks.json

For Duo CLI users, launch with project hooks enabled:

  glab duo cli --enable-project-hooks

To remove later: $0 --uninstall "$target"
EOF
